In [107]:
import pandas as pd
from numpy import *
#import numpy as np
num_websites = 5
num_users = 3
num_features = 5


In [108]:
pwd

'/home/velar/Documents/python'

In [109]:
user_ratings = pd.read_csv('/home/velar/Documents/python/user_rating.csv')

In [110]:
print (user_ratings)

       Unnamed: 0  Rajiv  Sujal  Rishabh
0      NepalStock  19.76  65.59    10.00
1        GSMArena  41.17  25.43    24.70
2      AceTravels   0.00   4.98     0.00
3        GoMovies   8.20   0.00    54.32
4  EducationNepal  30.87   4.00    10.98


In [111]:
user_rating_conversion = np.loadtxt(open("/home/velar/Documents/python/user_rating.csv", "rb"), delimiter=",", skiprows = 1, usecols = (1, 2, 3))

In [112]:
print(user_rating_conversion)

[[19.76 65.59 10.  ]
 [41.17 25.43 24.7 ]
 [ 0.    4.98  0.  ]
 [ 8.2   0.   54.32]
 [30.87  4.   10.98]]


In [113]:
user_did_rate = (user_rating_conversion !=0) *1

In [114]:
print(user_did_rate)

[[1 1 1]
 [1 1 1]
 [0 1 0]
 [1 0 1]
 [1 1 1]]


In [115]:
def normalized_rating(user_rating_conversion, user_did_rate):
    
    ratings_mean = np.zeros(shape = (num_websites, 1))
    ratings_norm = np.zeros(shape = (user_rating_conversion.shape))
    
    for i in range(num_websites):
        idx = np.where(user_did_rate[i] == 1)[0]
        ratings_mean[i] = np.mean(user_rating_conversion[i, idx])
        ratings_norm[i, idx] = user_rating_conversion[i, idx] - ratings_mean[i]
    
    return ratings_mean, ratings_norm
        
    
    
    
        
    

In [116]:
row_ko_mean_rate, normalized_rating = normalized_rating(user_rating_conversion, user_did_rate)

In [117]:
print(row_ko_mean_rate)

[[31.78333333]
 [30.43333333]
 [ 4.98      ]
 [31.26      ]
 [15.28333333]]


In [118]:
print(normalized_rating)

[[-12.02333333  33.80666667 -21.78333333]
 [ 10.73666667  -5.00333333  -5.73333333]
 [  0.           0.           0.        ]
 [-23.06         0.          23.06      ]
 [ 15.58666667 -11.28333333  -4.30333333]]


In [119]:
#this includes the user_features  
user_features = pd.read_csv('/home/velar/Documents/python/user_features.csv')
print (user_features)

  Unnamed: 0  Business  Mobile/Laptop  Consultancy  Travelling  Movies
0      Rajiv    0.1976         0.4117       0.3087      0.0000  0.0820
1      Sujal    0.6559         0.2543       0.0400      0.0498  0.0000
2    Rishabh    0.1000         0.2470       0.1098      0.0000  0.5432


In [120]:
user_features_conversion = np.loadtxt(open("/home/velar/Documents/python/user_features.csv", "rb"), delimiter=",", skiprows = 1, usecols = (1, 2, 3, 4, 5))
print(user_features_conversion)

[[0.1976 0.4117 0.3087 0.     0.082 ]
 [0.6559 0.2543 0.04   0.0498 0.    ]
 [0.1    0.247  0.1098 0.     0.5432]]


In [121]:
#this includes the websites features
websites_features =  pd.read_csv('/home/velar/Documents/python/website_features.csv')
print (websites_features)

       Unnamed: 0  Business  Mobile/Laptop  Consultancy  Travelling  Movies
0      NepalStock       1.0            0.1          0.1         0.1     0.1
1        GSMArena       0.1            1.0          0.1         0.1     0.1
2      AceTravels       0.1            0.1          0.1         1.0     0.1
3        GoMovies       0.1            0.1          0.1         0.1     1.0
4  EducationNepal       0.1            0.1          1.0         0.1     0.1


In [122]:
websites_features_conversion = np.loadtxt(open("/home/velar/Documents/python/website_features.csv", "rb"), delimiter=",", skiprows = 1, usecols = (1, 2, 3, 4, 5))
print(websites_features_conversion)

[[1.  0.1 0.1 0.1 0.1]
 [0.1 1.  0.1 0.1 0.1]
 [0.1 0.1 0.1 1.  0.1]
 [0.1 0.1 0.1 0.1 1. ]
 [0.1 0.1 1.  0.1 0.1]]


In [123]:
print(user_features_conversion)

[[0.1976 0.4117 0.3087 0.     0.082 ]
 [0.6559 0.2543 0.04   0.0498 0.    ]
 [0.1    0.247  0.1098 0.     0.5432]]


In [124]:
user_rated_features = (user_features_conversion != 0) *1
print(user_rated_features)

[[1 1 1 0 1]
 [1 1 1 1 0]
 [1 1 1 0 1]]


In [125]:
print(websites_features_conversion)

[[1.  0.1 0.1 0.1 0.1]
 [0.1 1.  0.1 0.1 0.1]
 [0.1 0.1 0.1 1.  0.1]
 [0.1 0.1 0.1 0.1 1. ]
 [0.1 0.1 1.  0.1 0.1]]


In [126]:
websites_features_mean = np.mean(websites_features_conversion, axis = 1)
newshape = (num_websites, 1)
mean_de_website_features = np.reshape(websites_features_mean, newshape)
print(mean_de_website_features)
    

[[0.28]
 [0.28]
 [0.28]
 [0.28]
 [0.28]]


In [127]:
normalized_websites_features = websites_features_conversion - mean_de_website_features

In [128]:
print(normalized_websites_features) # Website Features: (1 Business 2 Mobile/Laptop 3 Consultancy 4 Traveling 5 Movies) 

[[ 0.72 -0.18 -0.18 -0.18 -0.18]
 [-0.18  0.72 -0.18 -0.18 -0.18]
 [-0.18 -0.18 -0.18  0.72 -0.18]
 [-0.18 -0.18 -0.18 -0.18  0.72]
 [-0.18 -0.18  0.72 -0.18 -0.18]]


In [129]:
user_features_conversion # User Features: (1 Business 2 Mobile/Laptop 3 Consultancy 4 Traveling 5 Movies)

array([[0.1976, 0.4117, 0.3087, 0.    , 0.082 ],
       [0.6559, 0.2543, 0.04  , 0.0498, 0.    ],
       [0.1   , 0.247 , 0.1098, 0.    , 0.5432]])

In [130]:
user_features_conversion_mean = np.mean(user_features_conversion, axis = 1)
shape = (num_users, 1)
reshapedV2 = user_features_conversion_mean.reshape(shape)
print(reshapedV2)

[[0.2]
 [0.2]
 [0.2]]


In [131]:
fine_reshapedV2 = reshapedV2 *  user_rated_features
normalized_user_features = user_features_conversion - fine_reshapedV2
print(normalized_user_features)

#st = user_features_conversion - stpt
#print (st)
#stpt = reshapedV2 *  user_rated_features
#print (stpt)

[[-0.0024  0.2117  0.1087  0.     -0.118 ]
 [ 0.4559  0.0543 -0.16   -0.1502  0.    ]
 [-0.1     0.047  -0.0902  0.      0.3432]]


In [132]:
this_is_the_final_one = np.r_[normalized_websites_features.T.flatten(), normalized_user_features.T.flatten()]

In [133]:
print(this_is_the_final_one)

[ 0.72   -0.18   -0.18   -0.18   -0.18   -0.18    0.72   -0.18   -0.18
 -0.18   -0.18   -0.18   -0.18   -0.18    0.72   -0.18   -0.18    0.72
 -0.18   -0.18   -0.18   -0.18   -0.18    0.72   -0.18   -0.0024  0.4559
 -0.1     0.2117  0.0543  0.047   0.1087 -0.16   -0.0902  0.     -0.1502
  0.     -0.118   0.      0.3432]


In [134]:
def reconstruction(this_is_the_final_one, num_users, num_websites, num_features):
    first_25 = this_is_the_final_one[:num_websites * num_features] 
    websites_features = first_25.reshape(num_features, num_websites).transpose()
    last_15 = this_is_the_final_one[num_websites * num_features:]
    user_features = last_15.reshape(num_features, num_users).transpose()
    return websites_features, user_features #these are normalized web and user features

    

In [135]:
user_features_conversion

array([[0.1976, 0.4117, 0.3087, 0.    , 0.082 ],
       [0.6559, 0.2543, 0.04  , 0.0498, 0.    ],
       [0.1   , 0.247 , 0.1098, 0.    , 0.5432]])

In [136]:
print(user_did_rate)

[[1 1 1]
 [1 1 1]
 [0 1 0]
 [1 0 1]
 [1 1 1]]


In [137]:
#So, how do we actually come up with the line that best fits???
#That is the reason we use the gradient descent

# Gradient Descent:
#--> The minimum slope enables us to find the global minimum cost(the sum of squared error), 
#--> we go on decreasing descenting the slope until we find the lowest cost function(sum of squared error)
#--> The lowest sum of the squared error means the line of the best fit

def calculate_gradient(this_is_the_final_one, user_rating_conversion, user_did_rate, num_users, num_websites, num_features):
    websites_features, user_features= reconstruction(this_is_the_final_one, num_users, num_websites, num_features)
    
    #websites_features_grad = 5 * 5
    #user_features_grad = 
    
    #the dot product of websites_features and the user_features gives the user affinity:(lagav) for each of the genres
    difference = websites_features.dot(user_features.T) * user_did_rate - user_rating_conversion
    
    #we are calculating the partial_fraction(gradient(slope)) with respect to the cost function.
    
    websites_features_grad = difference.dot(user_features) 
    user_features_grad = difference.T.dot( websites_features ) 
    
    #wrap gradients back to the list
    return np.r_[websites_features_grad.T.flatten(), user_features_grad.T.flatten()]

    

In [138]:
def calculate_sum_of_squared_error(this_is_the_final_one, user_rating_conversion, user_did_rate, num_users, num_websites, num_features):
    websites_features, user_features = reconstruction(this_is_the_final_one, num_users, num_websites, num_features)
        
    #cost is the sum of squared distances between the axis and the line.
    #as shown, axis, or the plotted points are (X.dot(theta.t) * did_rate),
    #While the straight line is given by the ratings
    cost =  sum( (websites_features.dot(user_features.T) * user_did_rate - user_rating_conversion) ** 2 )/ 2
    
    # ** means an element wise power
    return cost

In [139]:
#a package used for advanced optimization, minimize cost function in this case
from scipy import optimize

#this makes website_predictions, from which we can make movie_recommendation
#optimize to the minimum value of the cost function
minimized_cost_and_optimal_params = optimize.fmin_cg(calculate_sum_of_squared_error, 
                                                     fprime=calculate_gradient, 
                                                      x0=this_is_the_final_one, 
                                                      args = (user_rating_conversion, user_did_rate,
                                                      num_users, num_websites, num_features),
                                                      maxiter = 100, disp = True, full_output = True)

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 17
         Function evaluations: 40
         Gradient evaluations: 40


In [140]:
cost, optimal_website_features_and_user_preferences = minimized_cost_and_optimal_params[1], minimized_cost_and_optimal_params[0]

In [141]:
websites_features, user_preferences = reconstruction(optimal_website_features_and_user_preferences, num_users, num_websites, num_features )

In [143]:
print(websites_features)

[[ 5.97598424  1.80463646 -1.69024352 -2.14427515  0.74978103]
 [ 1.84943152  4.68632068 -0.34599074 -2.50129938  1.03448037]
 [ 0.46715047 -0.10285615 -0.40704942  0.50692832 -0.2036593 ]
 [-1.60663829  1.9290811  -0.7771163  -1.20760318  4.92750011]
 [ 0.06564828  2.88428691  1.33514591 -1.81252597  0.0859413 ]]


In [144]:
all_predictions = websites_features.dot(user_preferences.T) #regular regression(y) = x.theta

In [145]:
print(all_predictions)

[[ 19.75999959  65.5900002   10.00000014]
 [ 41.16999992  25.4299998   24.69999989]
 [ -3.72850901   4.97999996  -4.34443127]
 [  8.19999989 -29.54060849  54.31999988]
 [ 30.86999968   3.99999992  10.97999991]]


In [156]:
predictions = all_predictions[:, 0:3] + row_ko_mean_rate

In [158]:
print(predictions)

[[51.54333293 97.37333354 41.78333347]
 [71.60333325 55.86333313 55.13333323]
 [ 1.25149099  9.95999996  0.63556873]
 [39.45999989  1.71939151 85.57999988]
 [46.15333301 19.28333325 26.26333325]]
